export const AUCTION_LIST_SET = "AUCTION_LIST_SET";
export const BID_AMOUNT_SET = "BID_AMOUNT_SET";
export const BIDDING_LIST_SET = "BIDDING_LIST_SET";
export const SET_AUCTIONED_ASSET = "SET_AUCTIONED_ASSET";
export const SET_SELECTED_AUCTIONED_ASSET = "SET_SELECTED_AUCTIONED_ASSET";

