export const tabsList = [
  {
    name: "Dashboard",
    value: "dashboard",
    langKey: "dashboard",
    path: "dashboard",
    active: "dashboard",
    index: 0,
  },
  {
    name: "My Positions",
    value: "home",
    langKey: "positions",
    path: "my-positions",
    active: "my-positions",
    index: 1,
  },
  {
    name: "Assets",
    value: "assets",
    langKey: "assets",
    path: "assets",
    active: "assets",
    index: 2,
  },
  {
    name: "mint",
    value: "borrow",
    langKey: "mint",
    path: "mint",
    active: "mint",
    index: 3,
  },
  {
    name: "earn",
    value: "earn-icon",
    langKey: "earn",
    path: "earn",
    active: "earn",
    index: 4,
  },
  {
    name: "auction",
    value: "auction-icon",
    langKey: "auction",
    path: "auctions",
    active: "auctions",
    index: 5,
  },
  {
    name: "more",
    value: "more",
    langKey: "more",
    path: "more",
    active: "more",
    index: 6,
  },
];
