export const SET_ALL_PROPOSAL = "SET_ALL_PROPOSAL";
export const SET_CURRENT_PROPOSAL = "SET_CURRENT_PROPOSAL";
export const SET_PROPOSAL_UP_DATA = "SET_PROPOSAL_UP_DATA";
export const SET_USER_VOTE = "SET_USER_VOTE";
export const SET_VOTE_COUNT = "SET_VOTE_COUNT";