export const POOLS_SET = "POOLS_SET";
export const POOL_SET = "POOL_SET";
export const POOL_BALANCE_SET = "POOL_BALANCE_SET";
export const POOL_DEPOSITS_SET = "POOL_DEPOSITS_SET";
export const SPOT_PRICE_SET = "SPOT_PRICE_SET";
export const POOL_BALANCE_FETCH_IN_PROGRESS = "POOL_BALANCE_FETCH_IN_PROGRESS";
export const FIRST_RESERVE_COIN_DENOM_SET = "FIRST_RESERVE_COIN_DENOM_SET";
export const SECOND_RESERVE_COIN_DENOM_SET = "SECOND_RESERVE_COIN_DENOM_SET";
export const POOL_TOKEN_SUPPLY_SET = "POOL_TOKEN_SUPPLY_SET";
export const POOL_BALANCES_SET = "POOL_BALANCES_SET";
export const POOLS_LIQUIDITY_LIST_SET = "POOLS_LIQUIDITY_LIST_SET";
export const BASE_COIN_POOL_PRICE_SET = "BASE_COIN_POOL_PRICE_SET";
export const POOL_PRICE_SET = "POOL_PRICE_SET";

