export const SET_WHITELISTED_ASSET = "SET_WHITELISTED_ASSET";
export const SET_ALL_WHITELISTED_ASSET = "SET_ALL_WHITELISTED_ASSET";
export const SET_ISLOCKER_EXIST = "SET_ISLOCKER_EXIST";
export const SET_USER_LOCKED_VALUE = "SET_USER_LOCKED_VALUE";
export const SET_SLIDER_TOOLTIP_VISIBLE = "SET_SLIDER_TOOLTIP_VISIBLE";
export const SET_EXTENDED_PAIR_ID = "SET_EXTENDED_PAIR_ID";
export const SET_EXTENDED_PAIR_VAULT_DATA_BY_ID =
  "SET_EXTENDED_PAIR_VAULT_DATA_BY_ID";
export const SET_SELECT_EXTENTED_PAIR_VAULT = "SET_SELECT_EXTENTED_PAIR_VAULT";
export const SET_CURRENT_PAIR_ID = "SET_CURRENT_PAIR_ID";
export const SET_OWNER_VAULT_ID = "SET_OWNER_VAULT_ID";
export const SET_OWNER_VAULT_INFO = "SET_OWNER_VAULT_INFO";
export const SET_ESTIMATED_LIQUIDATION_PRICE = "SET_ESTIMATED_LIQUIDATION_PRICE";
export const SET_COLLECTOR_DATA = "SET_COLLECTOR_DATA";
export const SET_LOCKER_DEFAULT_SELECT_TAB = "SET_LOCKER_DEFAULT_SELECT_TAB";
